### ISSUE TITLE
Package version

### ISSUE THREAD

**Issue by Dbgsaoge** [jadeCurl/Predicting-Viral-Rumors-and-Vulnerable-Users#1]
Hi，

Can you show all the requirement package and their version? The version of torch, torchmeta and dgl are not satisfied. Thanks!

**Comment by Dbgsaoge** [comment]
Additonally，can you show more details about the preprocessed dataset? Thanks!

**Comment by jadeCurl** [comment]
Hi, I've added a requirement file.
